#!/bin/sh

gitDescVer=$(git describe --tags --long --match "v[0-9]*")
gitDescVer=${gitDescVer:1}
gitDescVer=${gitDescVer/-/.}
gitDescVerHash=${gitDescVer: -9}
gitDescVer=${gitDescVer%$gitDescVerHash}
gitDescMajorVer=$(cut -d . -f 1 <<< $gitDescVer)
gitDescMinorVer=$(cut -d . -f 2 <<< $gitDescVer)
gitDescPatchVer=$(cut -d . -f 3 <<< $gitDescVer)

echo "New project version from git: $gitDescVer"

defGameIniFile=$(git rev-parse --show-toplevel)/Config/DefaultGame.ini
defGameIniFileVer=$(awk "/ProjectVersion=.*/{print $2}" $defGameIniFile)
defGameIniFileVer=${defGameIniFileVer:15}
defGameIniFileMajorVer=$(cut -d . -f 1 <<< $defGameIniFileVer)
defGameIniFileMinorVer=$(cut -d . -f 2 <<< $defGameIniFileVer)

if [ $defGameIniFileMajorVer -gt $gitDescMajorVer ]
then
    echo "Major version larger in 'defaultGame.ini' file. Incrementing version to that and creating new tag..."
    gitDescMajorVer=$defGameIniFileMajorVer
    gitDescMinorVer="0"
    gitDescPatchVer="0"
    git tag "v$gitDescMajorVer.$gitDescMinorVer"
elif [ $defGameIniFileMinorVer -gt $gitDescMinorVer ]
then
    echo "Minor version larger in 'defaultGame.ini' file. Incrementing version to that and creating new tag..."
    gitDescMinorVer=$defGameIniFileMinorVer
    gitDescPatchVer="0"
    git tag "v$gitDescMajorVer.$gitDescMinorVer"
fi

echo "New project version final: $gitDescMajorVer.$gitDescMinorVer.$gitDescPatchVer"
sed -i "s/ProjectVersion=[0-9]*.[0-9]*.[0-9]*/ProjectVersion=$gitDescMajorVer.$gitDescMinorVer.$gitDescPatchVer/" $defGameIniFile